// Generated by Website Factory (Dachsanierung & Gartenbau vertical). Update via the factory pipeline, not by hand.

export type GalabauUnit = "qm" | "lfm" | "stk" | "pauschal";

export type GalabauServiceKey =
  | "dachsanierung"
  | "dachreparatur"
  | "dachdaemmung"
  | "klempnerarbeiten"
  | "pflasterarbeiten"
  | "terrassenbau"
  | "gartenpflege";

export type GalabauService = {
  key: GalabauServiceKey;
  slug: string;
  label: string;
  navLabel: string;
  cta: string;
  unit: GalabauUnit;
  teaser: string;
  intro: string;
  bullets: string[];
  ablauf: { title: string; text: string }[];
  faq: { q: string; a: string }[];
  image: string;
  estimate: { minPerUnit: number; maxPerUnit: number; baseMin: number };
  seo: { title: string; description: string };
};

export type GalabauBudgetBand = {
  id: string;
  label: string;
  min: number;
  max: number | null;
};

export type GalabauConfig = {
  company: {
    name: string;
    city: string;
    foundedYear: string;
    teamSize: string;
    machines: string;
  };
  claim: string;
  heroSubline: string;
  services: GalabauService[];
  serviceArea: {
    centerCity: string;
    radiusKm: number;
    note: string;
    plzPrefixes: string[];
    borderPlzPrefixes: string[];
    places: string[];
    /** Map centre from the Google profile. Without it the map is skipped. */
    center?: { lat: number; lng: number };
  };
  contact: {
    phone: string;
    phoneLink: string;
    whatsapp: string;
    whatsappLink: string;
    whatsappPrefill: string;
    email: string;
    leadEmail: string;
  };
  estimator: {
    enabled: boolean;
    minProjectEur: number;
    currency: string;
    roundingStep: number;
    disclaimer: string;
    sizeThresholds: { klein: number; mittel: number };
    surcharges: { hanglage: number; schwererZugang: number; rueckbauBestand: number };
    budgetBands: GalabauBudgetBand[];
    realismQuestion: string;
    realismOptions: { id: string; label: string }[];
  };
  recruiting: {
    enabled: boolean;
    headline: string;
    teaser: string;
    intro: string;
    roles: string[];
    benefits: string[];
  };
  trust: {
    seals: { label: string; note: string }[];
    usps: { label: string; text: string }[];
  };
  assistant: {
    enabled: boolean;
    photoUploadMaxFiles: number;
    photoUploadMaxMb: number;
    consentText: string;
    responsePromise: string;
  };
};

export const galabau: GalabauConfig = {
  "company": {
    "name": "Dachsanierung & Gartenbau Kocer",
    "city": "Lampertheim",
    "foundedYear": "seit über 20 Jahren",
    "teamSize": "Familienbetrieb",
    "machines": ""
  },
  "claim": "Ein sicheres Dach, ein schöner Garten. Aus einer Hand.",
  "heroSubline": "Dachsanierung, Dachreparaturen, Klempnerarbeiten, Pflasterungen, Terrassen und Gartenpflege. Familienbetrieb in Lampertheim, seit über 20 Jahren rund um Ihr Zuhause tätig.",
  "services": [
    {
      "key": "dachsanierung",
      "slug": "dachsanierung",
      "label": "Dachsanierung & Neueindeckung",
      "navLabel": "Dachsanierung",
      "cta": "Dach begutachten lassen",
      "unit": "qm",
      "teaser": "Komplette Neueindeckung, Ziegel- und Flachdach, inklusive Unterspannbahn, Lattung und Anschlüssen.",
      "intro": "Ein saniertes Dach ist mehr als eine neue Ziegelreihe. Wir prüfen den kompletten Aufbau vom Gebälk über die Unterspannbahn bis zu Anschlüssen und Kaminen, und decken erst dann sinnvoll neu. So halten die nächsten Jahrzehnte wirklich.",
      "bullets": [
        "Steildach und Flachdach, Ton-, Beton- und Metallziegel",
        "Unterspannbahn, Lattung, Konterlattung und Dampfsperre",
        "Anschlüsse an Kamin, Gauben und Dachfenster fachgerecht ausgeführt",
        "Entsorgung des Altmaterials inklusive Container",
        "Gerüstbau und Absturzsicherung nach Vorschrift"
      ],
      "ablauf": [
        {
          "title": "Dachbegehung",
          "text": "Wir sehen uns Dachstuhl, Eindeckung, Anschlüsse und Traufbereich vor Ort an."
        },
        {
          "title": "Zustand & Umfang",
          "text": "Sanierung oder Neueindeckung? Wir sagen ehrlich, was wirklich nötig ist."
        },
        {
          "title": "Festpreis-Angebot",
          "text": "Positionen für Gerüst, Rückbau, Material und Einbau, getrennt ausgewiesen."
        },
        {
          "title": "Ausführung",
          "text": "Feste Bauzeit, Wetterschutz während der Arbeiten, saubere Baustellenübergabe."
        }
      ],
      "faq": [
        {
          "q": "Muss immer das ganze Dach neu?",
          "a": "Nein. Oft reichen Teilarbeiten wie eine neue Unterspannbahn, einzelne Reihen oder eine sanierte Kamineinfassung. Wir sagen offen, wann eine Reparatur ausreicht und wann sich die Sanierung nicht mehr aufhalten lässt."
        },
        {
          "q": "Wie lange dauert eine Neueindeckung?",
          "a": "Ein Einfamilienhausdach ist meist in einer bis drei Wochen fertig, abhängig von Größe, Zubehör und Witterung. Den Zeitrahmen legen wir vor Baubeginn fest."
        },
        {
          "q": "Kümmern Sie sich auch um Gerüst und Entsorgung?",
          "a": "Ja. Gerüst, Container und Entsorgung sind Teil unseres Angebots. Sie haben einen Ansprechpartner für die ganze Baustelle."
        }
      ],
      "image": "/assets/leistungen/gewerbliche-aussenanlagen.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 220,
        "baseMin": 3500
      },
      "seo": {
        "title": "Dachsanierung & Neueindeckung in Lampertheim | Dachsanierung & Gartenbau Kocer",
        "description": "Dachsanierung und Neueindeckung in Lampertheim: Ziegel- und Flachdach, Unterspannbahn, Anschlüsse, Gerüst und Entsorgung aus einer Hand."
      }
    },
    {
      "key": "dachreparatur",
      "slug": "dachreparatur",
      "label": "Dachreparaturen",
      "navLabel": "Reparatur",
      "cta": "Schaden melden",
      "unit": "pauschal",
      "teaser": "Undichte Stellen, Sturmschäden, gebrochene Ziegel: schnelle Reparatur, bevor der Schaden ins Haus wandert.",
      "intro": "Wenn ein Ziegel gebrochen ist oder Wasser durchkommt, zählt jede Woche. Wir schauen uns die Stelle zeitnah an, dichten sichere Übergangslösungen sofort ab und legen dann fest, ob eine Reparatur reicht oder ob mehr saniert werden muss.",
      "bullets": [
        "Undichte Stellen orten und dauerhaft schließen",
        "Sturm- und Hagelschäden inklusive Fotodokumentation für die Versicherung",
        "Einzelne Ziegel und Reihen tauschen, statt gleich das halbe Dach zu erneuern",
        "Notabdichtungen bei akuter Wasserfahrt möglich",
        "Anschlüsse an Kamin, Wandanschluss und Ortgang instand setzen"
      ],
      "ablauf": [
        {
          "title": "Anfrage",
          "text": "Sie schildern kurz, wo Wasser eintritt oder was beschädigt ist, Fotos helfen enorm."
        },
        {
          "title": "Ortstermin",
          "text": "Wir sehen uns das Dach an, oft mit Steiger oder Leiter, und finden die Ursache."
        },
        {
          "title": "Reparatur",
          "text": "Kleinere Arbeiten führen wir direkt aus, größere planen wir mit klarem Termin."
        },
        {
          "title": "Nachkontrolle",
          "text": "Beim nächsten starken Regen prüfen wir nach, dass die Stelle wirklich dicht ist."
        }
      ],
      "faq": [
        {
          "q": "Wie schnell können Sie kommen?",
          "a": "Bei akuten Wasserschäden versuchen wir, kurzfristig einen Termin einzuschieben. Rufen Sie uns direkt an, per Formular geht es meist zu langsam."
        },
        {
          "q": "Übernimmt die Versicherung die Reparatur?",
          "a": "Bei Sturm- und Hagelschäden ist das häufig der Fall. Wir dokumentieren die Schadstelle mit Fotos und einem nachvollziehbaren Angebot, sodass Ihre Versicherung damit arbeiten kann."
        }
      ],
      "image": "/assets/leistungen/gewerbliche-aussenanlagen.webp",
      "estimate": {
        "minPerUnit": 0,
        "maxPerUnit": 0,
        "baseMin": 350
      },
      "seo": {
        "title": "Dachreparaturen in Lampertheim | Dachsanierung & Gartenbau Kocer",
        "description": "Schnelle Dachreparaturen in Lampertheim: undichte Stellen, gebrochene Ziegel, Sturmschäden. Ehrliche Einschätzung, saubere Ausführung."
      }
    },
    {
      "key": "dachdaemmung",
      "slug": "dachdaemmung",
      "label": "Dachdämmung",
      "navLabel": "Dämmung",
      "cta": "Dämmung anfragen",
      "unit": "qm",
      "teaser": "Auf-, Zwischen- und Untersparrendämmung. Kalte Räume, hohe Heizkosten oder GEG-Nachrüstpflicht als Anlass.",
      "intro": "Eine gute Dachdämmung ist selten teurer als ein weiterer Winter mit ausgekühltem Obergeschoss. Wir prüfen den vorhandenen Aufbau, klären mit Ihnen die Zielsetzung (Wohnkomfort, Heizkosten, GEG) und wählen dann Dämmart und U-Wert mit Weitblick.",
      "bullets": [
        "Aufsparrendämmung bei ohnehin geplanter Neueindeckung",
        "Zwischen- und Untersparrendämmung ohne Eingriff ins Dach von außen",
        "Luftdichte Ebene mit Dampfbremse und geklebten Anschlüssen",
        "Dämmung der obersten Geschossdecke als preiswerte Alternative",
        "Hinweise zu Förderung (BEG, KfW) mit Empfehlung an Energieberatung"
      ],
      "ablauf": [
        {
          "title": "Bestand aufnehmen",
          "text": "Sparrenhöhe, Aufbau von innen und außen, Feuchtezustand des Gebälks prüfen."
        },
        {
          "title": "Konzept festlegen",
          "text": "Dämmart, Materialstärke, Dampfbremse und Anschlüsse werden gemeinsam besprochen."
        },
        {
          "title": "Angebot",
          "text": "Material, Einbau und ggf. Innenausbau als getrennte Positionen im Angebot."
        },
        {
          "title": "Einbau",
          "text": "Sauberer Einbau mit luftdichter Anschlussebene, Fotodokumentation auf Wunsch."
        }
      ],
      "faq": [
        {
          "q": "Muss ich mein Dach nach GEG dämmen?",
          "a": "Für viele Bestandsimmobilien greift eine Nachrüstpflicht der obersten Geschossdecke oder des Dachs. Wir prüfen den konkreten Fall und geben eine ehrliche Einschätzung, welche Variante bei Ihnen sinnvoll ist."
        },
        {
          "q": "Gibt es Förderung?",
          "a": "Ja, meist über die BEG-Einzelmaßnahme mit Einbindung einer Energieeffizienz-Expertin oder eines Experten. Wir zeigen den Weg, die formale Beantragung erledigt die Energieberatung."
        }
      ],
      "image": "/assets/leistungen/gewerbliche-aussenanlagen.webp",
      "estimate": {
        "minPerUnit": 60,
        "maxPerUnit": 180,
        "baseMin": 2500
      },
      "seo": {
        "title": "Dachdämmung in Lampertheim | Dachsanierung & Gartenbau Kocer",
        "description": "Dachdämmung in Lampertheim: Aufsparren-, Zwischen- und Untersparrendämmung mit dichter Anschlussebene. Ehrliche Beratung, saubere Ausführung."
      }
    },
    {
      "key": "klempnerarbeiten",
      "slug": "klempnerarbeiten",
      "label": "Klempner- & Spenglerarbeiten",
      "navLabel": "Klempner",
      "cta": "Rinnen prüfen lassen",
      "unit": "lfm",
      "teaser": "Dachrinnen, Fallrohre, Kaminverkleidung, Ortgang und Wandanschluss in Zink, Kupfer oder beschichtetem Stahl.",
      "intro": "Rinnen und Anschlüsse entscheiden darüber, wie lange ein Dach wirklich hält. Undichte Rinnen, gebrochene Fallrohre oder eine schadhafte Kamineinfassung sind kein Schönheitsfehler, sie führen Wasser in die Konstruktion. Wir arbeiten in Zink, Kupfer und beschichtetem Stahl.",
      "bullets": [
        "Dachrinnen und Fallrohre erneuern oder abschnittsweise reparieren",
        "Kamin-, Ortgang- und Wandanschlüsse dauerhaft dicht",
        "Materialien: Titanzink, Kupfer und beschichteter Stahl",
        "Vordächer, Attikaabdeckungen und Fensterbleche",
        "Prüfung der Entwässerung inklusive Anschluss an Fallrohr und Kanal"
      ],
      "ablauf": [
        {
          "title": "Bestand prüfen",
          "text": "Wir sehen uns Rinnen, Fallrohre und Anschlüsse an, oft von der Leiter oder mit Fernrohr."
        },
        {
          "title": "Umfang festlegen",
          "text": "Abschnittsweise erneuern oder komplett tauschen, klar begründet."
        },
        {
          "title": "Angebot",
          "text": "Material, Blechabwicklung und Montage werden getrennt ausgewiesen."
        },
        {
          "title": "Montage",
          "text": "Saubere Montage mit korrektem Gefälle, Prüfung mit Wasser vor der Übergabe."
        }
      ],
      "faq": [
        {
          "q": "Kupfer oder Zink?",
          "a": "Titanzink ist der langlebige Standard und optisch ruhig. Kupfer ist teurer, hält aber gefühlt ewig und passt zu bestimmten Fassaden. Wir zeigen beide Varianten an ausgeführten Häusern."
        },
        {
          "q": "Sind Rinnen einzeln reparierbar?",
          "a": "Häufig ja, mit sauberen Verlötungen oder einem Abschnittstausch. Wenn eine ganze Rinne verzogen oder korrodiert ist, macht ein kompletter Neuaufbau mehr Sinn. Wir sagen offen, was hält."
        }
      ],
      "image": "/assets/leistungen/gewerbliche-aussenanlagen.webp",
      "estimate": {
        "minPerUnit": 55,
        "maxPerUnit": 160,
        "baseMin": 600
      },
      "seo": {
        "title": "Klempner- & Spenglerarbeiten in Lampertheim | Dachsanierung & Gartenbau Kocer",
        "description": "Dachrinnen, Fallrohre und Anschlüsse in Zink, Kupfer und beschichtetem Stahl. Reparatur oder Neubau, saubere Übergabe."
      }
    },
    {
      "key": "pflasterarbeiten",
      "slug": "pflasterarbeiten",
      "label": "Pflaster- & Natursteinarbeiten",
      "navLabel": "Pflaster",
      "cta": "Fläche einschätzen lassen",
      "unit": "qm",
      "teaser": "Einfahrt, Hof, Vorgarten und Wege mit tragfähigem Unterbau, sauberer Entwässerung und passenden Materialien.",
      "intro": "Pflaster hält so lange, wie der Unterbau es zulässt. Wir bauen die Tragschicht auf die tatsächliche Belastung aus, planen das Gefälle mit und lösen die Entwässerung, bevor der erste Stein liegt. Beton, Naturstein oder Klinker: die Fläche entscheidet, nicht das Musterheft.",
      "bullets": [
        "Einfahrt, Zufahrt, Hof, Vorgarten und Wege",
        "Unterbau nach Belastung: PKW, Lieferverkehr, Wohnmobil",
        "Entwässerung, Rinnen und Anschluss an Bestandsflächen",
        "Randeinfassungen, L-Steine, Naturstein und Betonpflaster",
        "Referenzflächen in Lampertheim und Umgebung auf Wunsch vor Ort"
      ],
      "ablauf": [
        {
          "title": "Fläche melden",
          "text": "Grobe Quadratmeterzahl schätzen oder Fotos schicken, wir rechnen die Fläche nach."
        },
        {
          "title": "Aufbau festlegen",
          "text": "Wir klären Belastung, Untergrund und Entwässerung und wählen den passenden Aufbau."
        },
        {
          "title": "Angebot",
          "text": "Positionen für Aushub, Entsorgung, Tragschicht, Material und Einbau, getrennt ausgewiesen."
        },
        {
          "title": "Einbau",
          "text": "Aushub, Verdichtung, Verlegung, Abrütteln und Verfugen mit sauberer Baustellenübergabe."
        }
      ],
      "faq": [
        {
          "q": "Muss die alte Fläche raus?",
          "a": "Meist ja. Ein neues Pflaster auf altem, gesetztem Unterbau bekommt früher oder später Spurrillen. Wir prüfen den Bestand und sagen offen, ob ein Rückbau nötig ist."
        },
        {
          "q": "Wie viel Gefälle braucht die Fläche?",
          "a": "Als Faustwert rund zwei Prozent, weg vom Gebäude. Wo das nicht geht, planen wir Rinnen oder Versickerung ein."
        }
      ],
      "image": "/assets/leistungen/pflasterarbeiten-terrasse.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 210,
        "baseMin": 2500
      },
      "seo": {
        "title": "Pflaster- & Natursteinarbeiten in Lampertheim | Dachsanierung & Gartenbau Kocer",
        "description": "Pflaster- und Natursteinarbeiten für Einfahrt, Hof, Vorgarten und Wege. Tragfähiger Unterbau, saubere Entwässerung, saubere Randeinfassung."
      }
    },
    {
      "key": "terrassenbau",
      "slug": "terrassenbau",
      "label": "Terrassen & Dachterrassen",
      "navLabel": "Terrasse",
      "cta": "Terrasse anfragen",
      "unit": "qm",
      "teaser": "Terrassen und Dachterrassen aus Naturstein, Keramik oder Holz, inklusive Unterbau, Abdichtung und Entwässerung.",
      "intro": "Eine Terrasse ist der Teil des Zuhauses, der täglich benutzt wird. Bei Dachterrassen kommt die Abdichtung als eigenes Gewerk hinzu, hier zahlt sich unser Doppel aus Dach- und Gartenbau aus. Materialwahl, Untergrund und Entwässerung entscheiden, wie die Fläche nach fünf Jahren aussieht.",
      "bullets": [
        "Ebenerdige Terrassen und Dachterrassen aus einer Hand",
        "Materialien: Keramik, Naturstein, Betonplatten, Holz und WPC",
        "Unterbau: Splittbett, Stelzlager oder Punktfundamente",
        "Bei Dachterrassen: Abdichtung, Wurzelschutz und Entwässerung vor dem Belag",
        "Sichtschutz, Pergola und Beleuchtung mitgeplant"
      ],
      "ablauf": [
        {
          "title": "Wunsch klären",
          "text": "Größe, Nutzung, Sonne und gewünschtes Material, gern mit Inspirationsbildern."
        },
        {
          "title": "Untergrund prüfen",
          "text": "Wir schauen uns Anschlusshöhen, Türschwellen und Entwässerung vor Ort an."
        },
        {
          "title": "Angebot",
          "text": "Aufbau, Material und Zusatzleistungen wie Beleuchtung getrennt kalkuliert."
        },
        {
          "title": "Bau",
          "text": "Unterbau, Belag, Randabschluss, Reinigung und Übergabe."
        }
      ],
      "faq": [
        {
          "q": "Können Sie auch Dachterrassen?",
          "a": "Ja, das ist eine unserer Kernkompetenzen. Weil wir Dach und Terrasse selbst ausführen, gibt es keinen Schnittstellenstreit zwischen Dachdecker und Gartenbauer, wenn irgendwo Wasser eintritt."
        },
        {
          "q": "Holz oder Keramik?",
          "a": "Holz ist warm und lebendig, braucht aber Pflege. Keramik und Naturstein sind pflegeleicht und farbstabil. Wir zeigen beides an realen Flächen, bevor Sie sich festlegen."
        }
      ],
      "image": "/assets/leistungen/terrassenbau-grossformatplatten-01.webp",
      "estimate": {
        "minPerUnit": 140,
        "maxPerUnit": 380,
        "baseMin": 3500
      },
      "seo": {
        "title": "Terrassen & Dachterrassen in Lampertheim | Dachsanierung & Gartenbau Kocer",
        "description": "Terrassen und Dachterrassen aus Naturstein, Keramik oder Holz. Abdichtung, Entwässerung und Belag aus einer Hand."
      }
    },
    {
      "key": "gartenpflege",
      "slug": "gartenpflege",
      "label": "Gartenpflege & Baumfällung",
      "navLabel": "Garten",
      "cta": "Pflege anfragen",
      "unit": "qm",
      "teaser": "Einmalpflege, Pflegevertrag, Heckenschnitt und Baumfällung. Rasenpflege und Vorgartengestaltung inklusive.",
      "intro": "Pflege ist planbar. Wer feste Termine hat, spart den jährlichen Rückschnitt-Notfall. Wir machen beides: den einmaligen Einsatz, wenn der Garten aus dem Ruder gelaufen ist, und den Pflegevertrag über die Saison. Baumfällungen und Fällarbeiten übernehmen wir mit eigenem Gerät.",
      "bullets": [
        "Einmalpflege für verwilderte Gärten inklusive Entsorgung",
        "Pflegevertrag mit festen Terminen über die Saison",
        "Rasenpflege: Mähen, Vertikutieren, Nachsaat, Düngung",
        "Heckenschnitt, Formschnitt, Rückschnitt und Baumfällung",
        "Vorgartengestaltung, Beeteanlage und Rollrasen"
      ],
      "ablauf": [
        {
          "title": "Bestand ansehen",
          "text": "Fotos oder Ortstermin, damit der Aufwand realistisch eingeschätzt wird."
        },
        {
          "title": "Umfang festlegen",
          "text": "Einmalig oder Vertrag, mit klarer Liste, was enthalten ist."
        },
        {
          "title": "Termine",
          "text": "Feste Turnusse statt Zufall, Sie wissen wann wir kommen."
        },
        {
          "title": "Pflege",
          "text": "Ausführung inklusive Abtransport des Schnittguts."
        }
      ],
      "faq": [
        {
          "q": "Was kostet ein Pflegevertrag?",
          "a": "Das richtet sich nach Fläche, Heckenlänge und Turnus. Nach einem kurzen Blick auf die Fläche nennen wir einen festen Jahresbetrag."
        },
        {
          "q": "Wann wird die Hecke geschnitten?",
          "a": "Der Formschnitt erfolgt außerhalb der gesetzlichen Schonzeit. Radikale Rückschnitte sind nach BNatSchG vom 1. März bis 30. September nicht zulässig."
        },
        {
          "q": "Fällen Sie auch große Bäume?",
          "a": "Ja, im Rahmen unserer Möglichkeiten. Für sehr hohe oder schwer zugängliche Bäume ziehen wir bei Bedarf eine Kletterfirma hinzu und koordinieren die Baustelle für Sie."
        }
      ],
      "image": "/assets/leistungen/gartenpflege-heckenschnitt.webp",
      "estimate": {
        "minPerUnit": 3,
        "maxPerUnit": 12,
        "baseMin": 350
      },
      "seo": {
        "title": "Gartenpflege & Baumfällung in Lampertheim | Dachsanierung & Gartenbau Kocer",
        "description": "Gartenpflege als Einmalpflege oder Pflegevertrag: Rasen, Heckenschnitt, Baumfällung und Vorgartengestaltung mit festen Terminen."
      }
    }
  ],
  "serviceArea": {
    "centerCity": "Lampertheim",
    "radiusKm": 40,
    "note": "Wir arbeiten im Umkreis von rund 40 km um Lampertheim, unter anderem in Bürstadt, Biblis, Viernheim, Lorsch, Heppenheim, Mannheim, Ludwigshafen und Worms. Außerhalb prüfen wir Anfragen ab einer bestimmten Projektgröße einzeln.",
    "plzPrefixes": [
      "68"
    ],
    "borderPlzPrefixes": [
      "64",
      "67",
      "69"
    ],
    "places": [
      "Lampertheim",
      "Bürstadt",
      "Biblis",
      "Viernheim",
      "Lorsch",
      "Heppenheim",
      "Bensheim",
      "Mannheim",
      "Ludwigshafen",
      "Worms"
    ],
    "center": { "lat": 49.6045, "lng": 8.4700 }
  },
  "contact": {
    "phone": "06206 1306652",
    "phoneLink": "tel:+4962061306652",
    "whatsapp": "06206 1306652",
    "whatsappLink": "https://wa.me/4962061306652",
    "whatsappPrefill": "Hallo Familie Kocer, ich habe eine Frage zu einem Projekt in ",
    "email": "info@dg-kocer.de",
    "leadEmail": "info@dg-kocer.de"
  },
  "estimator": {
    "enabled": true,
    "minProjectEur": 500,
    "currency": "EUR",
    "roundingStep": 500,
    "disclaimer": "Alle Angaben sind eine unverbindliche Orientierung, kein Angebot. Der tatsächliche Preis hängt von Dachaufbau, Zugang, Untergrund, Entwässerung, Material und Ausführung ab und steht erst nach dem Ortstermin verbindlich fest.",
    "sizeThresholds": {
      "klein": 5000,
      "mittel": 20000
    },
    "surcharges": {
      "hanglage": 0.15,
      "schwererZugang": 0.12,
      "rueckbauBestand": 0.1
    },
    "budgetBands": [
      {
        "id": "bis-5k",
        "label": "bis 5.000 €",
        "min": 0,
        "max": 5000
      },
      {
        "id": "5-15k",
        "label": "5.000 bis 15.000 €",
        "min": 5000,
        "max": 15000
      },
      {
        "id": "15-30k",
        "label": "15.000 bis 30.000 €",
        "min": 15000,
        "max": 30000
      },
      {
        "id": "30-60k",
        "label": "30.000 bis 60.000 €",
        "min": 30000,
        "max": 60000
      },
      {
        "id": "ab-60k",
        "label": "mehr als 60.000 €",
        "min": 60000,
        "max": null
      },
      {
        "id": "unklar",
        "label": "Noch unklar",
        "min": 0,
        "max": null
      }
    ],
    "realismQuestion": "Wäre dieser grobe Rahmen für Sie grundsätzlich realistisch?",
    "realismOptions": [
      {
        "id": "passt",
        "label": "Ja, das passt so"
      },
      {
        "id": "guenstiger",
        "label": "Überraschend günstig"
      },
      {
        "id": "zu-hoch",
        "label": "Zu hoch"
      },
      {
        "id": "unklar",
        "label": "Noch unklar"
      }
    ]
  },
  "recruiting": {
    "enabled": true,
    "headline": "Dachdecker, Klempner oder Helfer im Handwerk?",
    "teaser": "In 60 Sekunden bewerben. Ohne Lebenslauf, ohne Anschreiben.",
    "intro": "Wir suchen Verstärkung für unsere Baustellen rund um Lampertheim, für das Dach genauso wie für Pflaster und Garten. Erzählen Sie uns kurz, was Sie können, den Rest klären wir am Telefon.",
    "roles": [
      "Dachdecker/in",
      "Klempner/in / Spengler/in",
      "Helfer/in im Handwerk",
      "Quereinsteiger/in",
      "Auszubildende/r"
    ],
    "benefits": [
      "Familienbetrieb statt Konzern, kurze Wege und ein Chef, den man kennt",
      "Feste Teams, keine wechselnden Kolonnen",
      "Pünktliche Bezahlung und geregelte Arbeitszeiten",
      "Baustellen im Umkreis, keine Wochenmontagen"
    ]
  },
  "trust": {
    "seals": [],
    "usps": [
      {
        "label": "Dach und Garten aus einer Hand",
        "text": "Kein Schnittstellenstreit zwischen Gewerken. Ein Ansprechpartner für die ganze Baustelle."
      },
      {
        "label": "Über 20 Jahre Erfahrung",
        "text": "Familienbetrieb mit gewachsenem Handwerk, nicht auf schnellen Wachstum getrimmt."
      },
      {
        "label": "Aufmaß vor Ort",
        "text": "Verbindliche Preise nennen wir erst, wenn wir das Dach oder die Fläche gesehen haben."
      }
    ]
  },
  "assistant": {
    "enabled": true,
    "photoUploadMaxFiles": 6,
    "photoUploadMaxMb": 8,
    "consentText": "Ich bin damit einverstanden, dass meine Angaben zur Bearbeitung meiner Anfrage gespeichert und verarbeitet werden. Die Daten werden nicht an Dritte weitergegeben.",
    "responsePromise": "Wir melden uns in der Regel innerhalb von 24 Stunden an Werktagen."
  }
};

export function findService(slug: string): GalabauService | undefined {
  return galabau.services.find((service) => service.slug === slug);
}

export default galabau;
