// Generated by Website Factory. Update via the factory pipeline, not by hand.

export type Review = {
  author: string;
  rating: number;
  text: string;
  time: string;
};

export type ReviewsData = {
  overallRating: number;
  totalRatings: number;
  reviews: Review[];
};

export const reviewsDataGeneratedFromFactory = true;

export const reviewsData: ReviewsData = {
  "overallRating": 5,
  "totalRatings": 11,
  "reviews": [
    {
      "author": "Karlheinz Vogel",
      "rating": 5,
      "text": "Herr Kocer hat bei mir bisher zwei Gewerke (1x komplettes Ziegeldach und 1x Dachentwässerung ) durchgeführt und in beiden Fällen eine qualitativ absolut hochwertige Leistung erbracht.\nDarüber hinaus schätze ich an Ihm, seine Beratungskompetenz, Verbindlichkeit und Seriosität. Das Preis-/Leistungsverhältnis ist m.E. ebenfalls gut, man bekommt eben eine anständige, ehrliche Arbeit für's Geld.\nDie Firma Kocer würde ich jederzeit vorbehaltlos weiter empfehlen.",
      "time": "vor 8 Monaten"
    },
    {
      "author": "Lusy Heiß",
      "rating": 5,
      "text": "Wir sind schon mehrere Jahre Kunde der Firma Kocer und haben diverse Sarnierungen an unserem Haus von ihnen durchführen lassen, darunter auch die Sarnierung des Daches sowie das Pflastern unseres Hofes und die Verlegung von Rollrasen im Garten. Ihre Zuverlässigkeit ist dabei herausragend, sie sind stets erreichbar und können die Aufträge auch zeitnah durchführen. Sie haben dabei unsere Erwartungen in jeglicher Hinsicht erfüllt und verdienen daher unsere vollste Empfehlung.",
      "time": "vor 2 Jahren"
    },
    {
      "author": "BS Mietservice GmbH",
      "rating": 5,
      "text": "Sehr kompetente Beratung und schnelle Umsetzung!\nUnsere Dachrinnen waren undicht. Das Problem wurde zügig und professionell behoben. Absolut empfehlenswert!",
      "time": "vor einem Jahr"
    },
    {
      "author": "Eva",
      "rating": 5,
      "text": "Herr Kocer und sein Vater arbeiten unheimlich genau und dennoch sehr flott! Pünktlichkeit und Zuverlässigkeit werden groß geschrieben! Wir haben unseren Garten und unsere Dachterrasse von den Herren Kocer machen lassen und sind unheimlich zufrieden!",
      "time": "vor 4 Jahren"
    },
    {
      "author": "W",
      "rating": 5,
      "text": "Kocer Dachsanierung & Gartenbau in Lampertheim ist ein sehr gutes und zuverlässiges Unternehmen, wer ein tolles Gartenbauunternehmen sucht, entscheidet Euch für Kocer.",
      "time": "vor 7 Jahren"
    }
  ]
};
